///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AmzInfTst
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AmzInfTstRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("c9ef1f1b-058d-4b24-90f1-1f58a977e74f")]
    public partial class AmzInfTstRepository : RepoGenBaseFolder
    {
        static AmzInfTstRepository instance = new AmzInfTstRepository();
        AmzInfTstRepositoryFolders.AmazonDeGuenstigePreiseFuerElektroAppFolder _amazondeguenstigepreisefuerelektro;

        /// <summary>
        /// Gets the singleton class instance representing the AmzInfTstRepository element repository.
        /// </summary>
        [RepositoryFolder("c9ef1f1b-058d-4b24-90f1-1f58a977e74f")]
        public static AmzInfTstRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AmzInfTstRepository() 
            : base("AmzInfTstRepository", "/", null, 0, false, "c9ef1f1b-058d-4b24-90f1-1f58a977e74f", ".\\RepositoryImages\\AmzInfTstRepositoryc9ef1f1b.rximgres")
        {
            _amazondeguenstigepreisefuerelektro = new AmzInfTstRepositoryFolders.AmazonDeGuenstigePreiseFuerElektroAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c9ef1f1b-058d-4b24-90f1-1f58a977e74f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The AmazonDeGuenstigePreiseFuerElektro folder.
        /// </summary>
        [RepositoryFolder("a50d62e1-3980-458c-9835-5f74e1b975b0")]
        public virtual AmzInfTstRepositoryFolders.AmazonDeGuenstigePreiseFuerElektroAppFolder AmazonDeGuenstigePreiseFuerElektro
        {
            get { return _amazondeguenstigepreisefuerelektro; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class AmzInfTstRepositoryFolders
    {
        /// <summary>
        /// The AmazonDeGuenstigePreiseFuerElektroAppFolder folder.
        /// </summary>
        [RepositoryFolder("a50d62e1-3980-458c-9835-5f74e1b975b0")]
        public partial class AmazonDeGuenstigePreiseFuerElektroAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clientInfo;
            RepoItemInfo _zurueckInfo;

            /// <summary>
            /// Creates a new AmazonDeGuenstigePreiseFuerElektro  folder.
            /// </summary>
            public AmazonDeGuenstigePreiseFuerElektroAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AmazonDeGuenstigePreiseFuerElektro", "/form[@title~'^Amazon\\.de:\\ Günstige\\ Preis']", parentFolder, 30000, null, true, "a50d62e1-3980-458c-9835-5f74e1b975b0", "")
            {
                _clientInfo = new RepoItemInfo(this, "Client", "container[@accessiblename~'^Amazon\\.de:\\ Günstige\\ Preis']/container/container[1]", 30000, null, "46610d5c-8420-4cfb-a005-3955a81cab2a");
                _zurueckInfo = new RepoItemInfo(this, "Zurueck", "container[@accessiblename~'^Amazon\\ Anmelden\\ -\\ Google\\ ']/container[@accessiblename='Google Chrome']//button[@accessiblename='Zurück']", 30000, null, "5e0d4251-1208-4838-819e-4eab62e7f8dc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a50d62e1-3980-458c-9835-5f74e1b975b0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a50d62e1-3980-458c-9835-5f74e1b975b0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Client item.
            /// </summary>
            [RepositoryItem("46610d5c-8420-4cfb-a005-3955a81cab2a")]
            public virtual Ranorex.Container Client
            {
                get
                {
                    return _clientInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Client item info.
            /// </summary>
            [RepositoryItemInfo("46610d5c-8420-4cfb-a005-3955a81cab2a")]
            public virtual RepoItemInfo ClientInfo
            {
                get
                {
                    return _clientInfo;
                }
            }

            /// <summary>
            /// The Zurueck item.
            /// </summary>
            [RepositoryItem("5e0d4251-1208-4838-819e-4eab62e7f8dc")]
            public virtual Ranorex.Button Zurueck
            {
                get
                {
                    return _zurueckInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Zurueck item info.
            /// </summary>
            [RepositoryItemInfo("5e0d4251-1208-4838-819e-4eab62e7f8dc")]
            public virtual RepoItemInfo ZurueckInfo
            {
                get
                {
                    return _zurueckInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}