///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AmzInfTst
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenBrowser recording.
    /// </summary>
    [TestModule("9314ee24-4cc5-4c04-a583-84fad5d6b187", ModuleType.Recording, 1)]
    public partial class OpenBrowser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AmzInfTstRepository repository.
        /// </summary>
        public static AmzInfTstRepository repo = AmzInfTstRepository.Instance;

        static OpenBrowser instance = new OpenBrowser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenBrowser()
        {
            basis_url = "https://www.amazon.de/";
            browser = "Chrome";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenBrowser Instance
        {
            get { return instance; }
        }

#region Variables

        string _basis_url;

        /// <summary>
        /// Gets or sets the value of variable basis_url.
        /// </summary>
        [TestVariable("c3df2ed4-c060-4e97-a52b-79e9056623a8")]
        public string basis_url
        {
            get { return _basis_url; }
            set { _basis_url = value; }
        }

        string _browser;

        /// <summary>
        /// Gets or sets the value of variable browser.
        /// </summary>
        [TestVariable("93c0cda3-45b1-4f2a-8838-8ee7666e1525")]
        public string browser
        {
            get { return _browser; }
            set { _browser = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site URL in variable $basis_url with browser specified by variable $browser in maximized mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser(basis_url, browser, "", false, true, false, true, false);
            Delay.Milliseconds(11940);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AmazonDeGuenstigePreiseFuerElektro.Client' at 1617;218.", repo.AmazonDeGuenstigePreiseFuerElektro.ClientInfo, new RecordItemIndex(1));
            repo.AmazonDeGuenstigePreiseFuerElektro.Client.Click("1617;218");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'detlef'.", new RecordItemIndex(2));
            Keyboard.Press("detlef");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.kossakowski{LControlKey down}{RMenu down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}gmx.net'.", new RecordItemIndex(3));
            Keyboard.Press(".kossakowski{LControlKey down}{RMenu down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}gmx.net");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AmazonDeGuenstigePreiseFuerElektro.Client1' at 1090;312.", repo.AmazonDeGuenstigePreiseFuerElektro.Client1Info, new RecordItemIndex(4));
            repo.AmazonDeGuenstigePreiseFuerElektro.Client1.Click("1090;312");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1Q2w3e4r{Return}'.", new RecordItemIndex(5));
            Keyboard.Press("1Q2w3e4r{Return}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
